feat: server
strapi-community/strapi-plugin-search pull request #9
Opened 2023-08-10 00:52 UTC by ComfortablyCoding

2023-08-10 20:49 UTC, itsnoa04 commented on packages/strapi-plugin-search/server/bootstrap/bootstrap-lifecycles.ts
> +        async afterUpdate(event) {
Why are we not indexing search index in before update?
If search indexing fails are we still going to let the entry be created?

2023-08-10 21:27 UTC, itsnoa04 requested changes
lets talk about the comment

2023-08-11 17:03 UTC, ComfortablyCoding commented on packages/strapi-plugin-search/server/bootstrap/bootstrap-lifecycles.ts
> +        async afterUpdate(event) {
As discussed we should not prevent create or update if an index fails. Instead we should allow it to happen and if the index errors we show a toast notifying an error occured with the index.

We should (at some point) add an option for re-indexing a specific content type record. This will be done via an injection zone.

2023-08-11 17:03 UTC, itsnoa04 approved these changes

2023-08-11 17:07 UTC, itsnoa04 commented
LGTM!

2023-08-11 17:09 UTC, merged